# Generated by Django 3.2.5 on 2022-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('marks', models.IntegerField()),
                ('asked', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
